{
  theme,
  lib,
  config,
  pkgs,
  ...
}:
let
  themeName = "nix-theme";

  # Helper to add alpha to a hex color: base hex + "cc" = ~80% opacity
  withAlpha = hex: suffix: "${hex}${suffix}";

  themeJson = builtins.toJSON {
    "$schema" = "https://zed.dev/schema/themes/v0.2.0.json";
    name = themeName;
    author = "generated by home-manager";
    themes = [
      {
        name = themeName;
        appearance = "dark";
        style = {
          # ── Base UI surfaces ──────────────────────────────────────────
          "background"                        = theme.base00;
          "elevated_surface.background"       = theme.base01;
          "surface.background"                = theme.base01;
          "element.background"                = theme.base01;
          "element.hover"                     = withAlpha theme.base02 "cc";
          "element.active"                    = theme.base02;
          "element.selected"                  = theme.base02;
          "element.disabled"                  = withAlpha theme.base03 "88";
          "drop_target.background"            = withAlpha theme.base0D "33";

          # ── Ghost elements (subtle interactive areas) ─────────────────
          "ghost_element.background"          = "transparent";
          "ghost_element.hover"               = withAlpha theme.base02 "88";
          "ghost_element.active"              = withAlpha theme.base02 "cc";
          "ghost_element.selected"            = withAlpha theme.base02 "cc";
          "ghost_element.disabled"            = withAlpha theme.base03 "44";

          # ── Text ──────────────────────────────────────────────────────
          "text"                              = theme.base05;
          "text.muted"                        = theme.base04;
          "text.placeholder"                  = theme.base03;
          "text.disabled"                     = theme.base03;
          "text.accent"                       = theme.base0D;
          "link_text.hover"                   = theme.base0D;

          # ── Icons ─────────────────────────────────────────────────────
          "icon"                              = theme.base05;
          "icon.muted"                        = theme.base03;
          "icon.disabled"                     = theme.base03;
          "icon.placeholder"                  = theme.base03;
          "icon.accent"                       = theme.base0D;

          # ── Borders ───────────────────────────────────────────────────
          "border"                            = theme.base02;
          "border.variant"                    = theme.base01;
          "border.focused"                    = theme.base0D;
          "border.selected"                   = theme.base0D;
          "border.transparent"                = "transparent";
          "border.disabled"                   = theme.base02;

          # ── Editor ───────────────────────────────────────────────────
          "editor.background"                 = theme.base00;
          "editor.gutter.background"          = theme.base00;
          "editor.subheader.background"       = theme.base01;
          "editor.active_line.background"     = withAlpha theme.base01 "cc";
          "editor.highlighted_line.background" = withAlpha theme.base02 "55";
          "editor.line_number"                = theme.base03;
          "editor.active_line_number"         = theme.base05;
          "editor.invisible"                  = theme.base03;
          "editor.wrap_guide"                 = withAlpha theme.base02 "88";
          "editor.active_wrap_guide"          = theme.base02;
          "editor.document_highlight.read_background"  = withAlpha theme.base0D "22";
          "editor.document_highlight.write_background" = withAlpha theme.base0E "22";

          # ── Cursor & Selection ────────────────────────────────────────
          "editor.foreground"                 = theme.base05;
          "selection.background"              = withAlpha theme.base02 "cc";
          "search.match_background"           = withAlpha theme.base0A "44";

          # ── Terminal ─────────────────────────────────────────────────
          "terminal.background"               = theme.base00;
          "terminal.foreground"               = theme.base05;
          "terminal.bright_foreground"        = theme.base05;
          "terminal.dim_foreground"           = theme.base03;
          "terminal.ansi.black"               = theme.base02;
          "terminal.ansi.red"                 = theme.base08;
          "terminal.ansi.green"               = theme.base0B;
          "terminal.ansi.yellow"              = theme.base0A;
          "terminal.ansi.blue"                = theme.base0D;
          "terminal.ansi.magenta"             = theme.base0E;
          "terminal.ansi.cyan"                = theme.base0C;
          "terminal.ansi.white"               = theme.base05;
          "terminal.ansi.bright_black"        = theme.base03;
          "terminal.ansi.bright_red"          = theme.base08;
          "terminal.ansi.bright_green"        = theme.base0B;
          "terminal.ansi.bright_yellow"       = theme.base0A;
          "terminal.ansi.bright_blue"         = theme.base0D;
          "terminal.ansi.bright_magenta"      = theme.base0E;
          "terminal.ansi.bright_cyan"         = theme.base0C;
          "terminal.ansi.bright_white"        = theme.base07;

          # ── Status bar ───────────────────────────────────────────────
          "status_bar.background"             = theme.base01;
          "title_bar.background"              = theme.base01;
          "title_bar.inactive_background"     = theme.base00;
          "toolbar.background"                = theme.base00;
          "tab_bar.background"                = theme.base01;
          "tab.inactive_background"           = theme.base01;
          "tab.active_background"             = theme.base00;

          # ── Panels & panes ────────────────────────────────────────────
          "panel.background"                  = theme.base01;
          "panel.focused_border"              = theme.base0D;
          "pane.focused_border"               = theme.base0D;

          # ── Scrollbar ────────────────────────────────────────────────
          "scrollbar.thumb.background"        = withAlpha theme.base04 "88";
          "scrollbar.thumb.hover_background"  = theme.base04;
          "scrollbar.thumb.border"            = withAlpha theme.base04 "88";
          "scrollbar.track.background"        = "transparent";
          "scrollbar.track.border"            = withAlpha theme.base02 "55";

          # ── Git ───────────────────────────────────────────────────────
          "created"                           = theme.base0B;
          "created.background"                = withAlpha theme.base0B "22";
          "created.border"                    = withAlpha theme.base0B "88";
          "modified"                          = theme.base0A;
          "modified.background"               = withAlpha theme.base0A "22";
          "modified.border"                   = withAlpha theme.base0A "88";
          "deleted"                           = theme.base08;
          "deleted.background"                = withAlpha theme.base08 "22";
          "deleted.border"                    = withAlpha theme.base08 "88";
          "conflict"                          = theme.base09;
          "conflict.background"               = withAlpha theme.base09 "22";
          "conflict.border"                   = withAlpha theme.base09 "88";
          "hidden"                            = theme.base03;
          "hidden.background"                 = theme.base01;
          "hidden.border"                     = theme.base02;
          "ignored"                           = theme.base03;
          "ignored.background"                = theme.base01;
          "ignored.border"                    = theme.base02;
          "renamed"                           = theme.base0D;
          "renamed.background"                = withAlpha theme.base0D "22";
          "renamed.border"                    = withAlpha theme.base0D "88";

          # ── Diagnostics ───────────────────────────────────────────────
          "error"                             = theme.base08;
          "error.background"                  = withAlpha theme.base08 "22";
          "error.border"                      = withAlpha theme.base08 "88";
          "warning"                           = theme.base0A;
          "warning.background"                = withAlpha theme.base0A "22";
          "warning.border"                    = withAlpha theme.base0A "88";
          "info"                              = theme.base0D;
          "info.background"                   = withAlpha theme.base0D "22";
          "info.border"                       = withAlpha theme.base0D "88";
          "hint"                              = theme.base0C;
          "hint.background"                   = withAlpha theme.base0C "22";
          "hint.border"                       = withAlpha theme.base0C "88";
          "predictive"                        = theme.base03;
          "predictive.background"             = withAlpha theme.base0C "22";
          "predictive.border"                 = withAlpha theme.base0C "88";

          # ── Accents (indent guides, multi-cursor colors) ───────────────
          "accents" = [
            theme.base08 theme.base09 theme.base0A
            theme.base0B theme.base0C theme.base0D theme.base0E
          ];

          # ── Syntax ───────────────────────────────────────────────────
          syntax = {
            "attribute"         = { color = theme.base09; };
            "boolean"           = { color = theme.base09; };
            "comment"           = { color = theme.base03; font_style = "italic"; };
            "comment.doc"       = { color = theme.base04; font_style = "italic"; };
            "constant"          = { color = theme.base09; };
            "constructor"       = { color = theme.base0D; };
            "embedded"          = { color = theme.base0E; };
            "emphasis"          = { color = theme.base0A; };
            "emphasis.strong"   = { color = theme.base0A; font_weight = 700; };
            "enum"              = { color = theme.base09; };
            "function"          = { color = theme.base0D; };
            "function.builtin"  = { color = theme.base0D; };
            "function.special.definition" = { color = theme.base0E; };
            "hint"              = { color = theme.base03; font_style = "italic"; };
            "keyword"           = { color = theme.base0E; };
            "label"             = { color = theme.base0A; };
            "link_text"         = { color = theme.base0B; font_style = "italic"; };
            "link_uri"          = { color = theme.base0C; };
            "number"            = { color = theme.base09; };
            "operator"          = { color = theme.base0C; };
            "predictive"        = { color = theme.base03; font_style = "italic"; };
            "predoc"            = { color = theme.base04; };
            "primary"           = { color = theme.base05; };
            "property"          = { color = theme.base05; };
            "punctuation"       = { color = theme.base05; };
            "punctuation.bracket" = { color = theme.base05; };
            "punctuation.delimiter" = { color = theme.base05; };
            "punctuation.list_marker" = { color = theme.base0E; };
            "punctuation.special" = { color = theme.base0C; };
            "string"            = { color = theme.base0B; };
            "string.doc"        = { color = theme.base0B; font_style = "italic"; };
            "string.escape"     = { color = theme.base0C; };
            "string.regex"      = { color = theme.base0C; };
            "string.special"    = { color = theme.base0C; };
            "string.special.symbol" = { color = theme.base0B; };
            "tag"               = { color = theme.base08; };
            "text.literal"      = { color = theme.base0B; };
            "title"             = { color = theme.base0D; font_weight = 700; };
            "type"              = { color = theme.base0A; };
            "type.builtin"      = { color = theme.base0A; };
            "variable"          = { color = theme.base05; };
            "variable.builtin"  = { color = theme.base09; };
            "variable.member"   = { color = theme.base05; };
            "variable.special"  = { color = theme.base0E; };
            "variant"           = { color = theme.base0E; };
          };
        };
      }
    ];
  };

in
{
  home.file.".config/zed/themes/${themeName}.json" = {
    force = true;
    text = themeJson;
  };
}
