# zed-theme.nix
# Generates a Zed editor theme from your base16 theme attrset.
#
# BASE16 → ZED MAPPING REFERENCE:
#   base00 = background (darkest)
#   base01 = elevated surfaces, panels
#   base02 = borders, selections, surface highlights
#   base03 = comments, muted/disabled text, overlays   (≈ catppuccin overlay1)
#   base04 = muted icons, secondary text               (≈ catppuccin subtext0)
#   base05 = primary text, variables
#   base06 = rosewater / flamingo — used for special strings, notes
#   base07 = lavender — used for fields, link_text, player accents
#   base08 = red   → errors, deleted, variable.builtin, diff.minus
#   base09 = peach → constants, numbers, booleans, attributes
#   base0A = yellow → types, modules, tag.attribute, warnings
#   base0B = green  → strings, created, diff.plus, success
#   base0C = teal   → operators, macros, labels, search.match
#   base0D = blue   → functions, tags, properties, info, links
#   base0E = mauve  → keywords, type.builtin, accents, cursor
#   base0F = flamingo → constructors, special strings/symbols
#
# APPROXIMATION NOTES:
#   - Catppuccin uses ~30 named colors; base16 only gives us 16.
#   - "parameter" / "emphasis" / "primary" / "embedded" in catppuccin use a
#     desaturated red (eba0ac). We use base08 as the closest match.
#   - "punctuation" / "comment" in catppuccin use overlay1 (a mid-gray between
#     base02 and base03). We use base03 — slightly darker, acceptable.
#   - "operator" / "keyword.export" in catppuccin use sky blue (89dceb),
#     distinct from teal. We use base0C (teal) — very close.
#   - "string.special.*" uses pink (f5c2e7 ≈ catppuccin pink). We use base0E.
#   - Players use the full accent palette; we cycle through base0E, base07,
#     base0D, base0C, base0B, base0A, base09, base08.

{
  theme,
  lib,
  config,
  pkgs,
  ...
}:
let
  themeName = "nix-theme";

  # Appends a 2-digit hex alpha suffix to a #RRGGBB color → #RRGGBBAA
  # Zed accepts 8-digit hex for transparency.
  a = color: suffix: "${color}${suffix}";

  themeJson = builtins.toJSON {
    "$schema" = "https://zed.dev/schema/themes/v0.2.0.json";
    name = themeName;
    author = "generated by home-manager";
    themes = [
      {
        name = themeName;
        appearance = "dark";
        style = {

          # ── Accent palette (indent guides, multi-cursor ring colors) ───────
          accents = [
            theme.base0E  # mauve
            theme.base07  # lavender
            theme.base0C  # teal
            theme.base0B  # green
            theme.base0A  # yellow
            theme.base09  # peach
            theme.base08  # red
          ];

          # ── Vim mode indicator colors ──────────────────────────────────────
          "vim.mode.text"                  = theme.base00;
          "vim.normal.foreground"          = theme.base00;
          "vim.helix_normal.foreground"    = theme.base00;
          "vim.visual.foreground"          = theme.base00;
          "vim.helix_select.foreground"    = theme.base00;
          "vim.insert.foreground"          = theme.base00;
          "vim.visual_line.foreground"     = theme.base00;
          "vim.visual_block.foreground"    = theme.base00;
          "vim.replace.foreground"         = theme.base00;
          "vim.normal.background"          = theme.base06;  # rosewater
          "vim.helix_normal.background"    = theme.base06;
          "vim.visual.background"          = theme.base07;  # lavender
          "vim.helix_select.background"    = theme.base07;
          "vim.insert.background"          = theme.base0B;  # green
          "vim.visual_line.background"     = theme.base07;
          "vim.visual_block.background"    = theme.base0E;  # mauve
          "vim.replace.background"         = theme.base08;  # red

          # ── Window / surface chrome ────────────────────────────────────────
          "background.appearance"          = "opaque";
          "background"                     = theme.base00;
          "elevated_surface.background"    = theme.base01;
          "surface.background"             = theme.base01;

          # ── Generic interactive elements ───────────────────────────────────
          "element.background"             = theme.base00;
          "element.hover"                  = theme.base02;
          "element.active"                 = a theme.base02 "4d";
          "element.selected"               = a theme.base02 "4d";
          "element.disabled"               = theme.base03;
          "drop_target.background"         = a theme.base02 "66";

          "ghost_element.background"       = "#00000000";
          "ghost_element.hover"            = a theme.base02 "4d";
          "ghost_element.active"           = a theme.base03 "99";
          "ghost_element.selected"         = a theme.base03 "66";
          "ghost_element.disabled"         = theme.base03;

          # ── Text ───────────────────────────────────────────────────────────
          "text"                           = theme.base05;
          "text.muted"                     = theme.base04;
          "text.placeholder"               = theme.base03;
          "text.disabled"                  = a theme.base03 "aa";
          "text.accent"                    = theme.base0E;
          "link_text.hover"                = theme.base0C;  # sky/teal

          # ── Icons ──────────────────────────────────────────────────────────
          "icon"                           = theme.base05;
          "icon.muted"                     = theme.base04;
          "icon.disabled"                  = theme.base03;
          "icon.placeholder"               = theme.base03;
          "icon.accent"                    = theme.base0E;

          # ── Borders ────────────────────────────────────────────────────────
          "border"                         = theme.base02;
          "border.variant"                 = a theme.base0E "88";
          "border.focused"                 = theme.base07;  # lavender
          "border.selected"                = theme.base0E;  # mauve
          "border.transparent"             = theme.base0B;  # green
          "border.disabled"                = theme.base03;

          # ── Status / title bars ────────────────────────────────────────────
          "status_bar.background"          = theme.base00;
          "title_bar.background"           = theme.base00;
          "title_bar.inactive_background"  = a theme.base00 "dd";
          "toolbar.background"             = theme.base01;
          "tab_bar.background"             = theme.base00;
          "tab.inactive_background"        = a theme.base00 "aa";
          "tab.active_background"          = theme.base01;

          # ── Search ─────────────────────────────────────────────────────────
          "search.match_background"        = a theme.base0C "4d";
          "search.active_match_background" = a theme.base08 "4d";

          # ── Panels & panes ─────────────────────────────────────────────────
          "panel.background"               = theme.base01;
          "panel.focused_border"           = theme.base05;
          "panel.indent_guide"             = a theme.base02 "99";
          "panel.indent_guide_active"      = theme.base03;
          "panel.indent_guide_hover"       = theme.base0E;
          "panel.overlay_background"       = theme.base01;
          "pane.focused_border"            = theme.base05;
          "pane_group.border"              = theme.base02;

          # ── Scrollbar ──────────────────────────────────────────────────────
          "scrollbar.thumb.background"     = a theme.base03 "80";
          "scrollbar.thumb.hover_background" = theme.base03;
          "scrollbar.thumb.active_background" = null;
          "scrollbar.thumb.border"         = null;
          "scrollbar.track.background"     = theme.base00;
          "scrollbar.track.border"         = a theme.base05 "12";

          # ── Minimap ────────────────────────────────────────────────────────
          "minimap.thumb.background"       = a theme.base0E "33";
          "minimap.thumb.hover_background" = a theme.base0E "66";
          "minimap.thumb.active_background" = a theme.base0E "99";
          "minimap.thumb.border"           = null;

          # ── Editor ────────────────────────────────────────────────────────
          "editor.foreground"              = theme.base05;
          "editor.background"              = theme.base01;
          "editor.gutter.background"       = theme.base01;
          "editor.subheader.background"    = theme.base00;
          "editor.active_line.background"  = a theme.base05 "12";
          "editor.highlighted_line.background" = null;
          "editor.line_number"             = theme.base03;
          "editor.active_line_number"      = theme.base0E;
          "editor.invisible"               = a theme.base03 "66";
          "editor.wrap_guide"              = theme.base02;
          "editor.active_wrap_guide"       = theme.base02;
          "editor.document_highlight.bracket_background" = a theme.base0E "17";
          "editor.document_highlight.read_background"    = a theme.base05 "29";
          "editor.document_highlight.write_background"   = a theme.base05 "29";
          "editor.indent_guide"            = a theme.base02 "99";
          "editor.indent_guide_active"     = theme.base03;

          # ── Debugger ───────────────────────────────────────────────────────
          "debugger.accent"                = theme.base08;
          "editor.debugger_active_line.background" = a theme.base09 "12";

          # ── Terminal ───────────────────────────────────────────────────────
          "terminal.background"            = theme.base01;
          "terminal.ansi.background"       = theme.base01;
          "terminal.foreground"            = theme.base05;
          "terminal.dim_foreground"        = theme.base04;
          "terminal.bright_foreground"     = theme.base05;
          "terminal.ansi.black"            = theme.base02;
          "terminal.ansi.white"            = theme.base04;
          "terminal.ansi.red"              = theme.base08;
          "terminal.ansi.green"            = theme.base0B;
          "terminal.ansi.yellow"           = theme.base0A;
          "terminal.ansi.blue"             = theme.base0D;
          "terminal.ansi.magenta"          = theme.base0E;
          "terminal.ansi.cyan"             = theme.base0C;
          "terminal.ansi.bright_black"     = theme.base03;
          "terminal.ansi.bright_white"     = theme.base05;
          "terminal.ansi.bright_red"       = theme.base08;
          "terminal.ansi.bright_green"     = theme.base0B;
          "terminal.ansi.bright_yellow"    = theme.base0A;
          "terminal.ansi.bright_blue"      = theme.base0D;
          "terminal.ansi.bright_magenta"   = theme.base0E;
          "terminal.ansi.bright_cyan"      = theme.base0C;
          "terminal.ansi.dim_black"        = theme.base02;
          "terminal.ansi.dim_white"        = theme.base04;
          "terminal.ansi.dim_red"          = theme.base08;
          "terminal.ansi.dim_green"        = theme.base0B;
          "terminal.ansi.dim_yellow"       = theme.base0A;
          "terminal.ansi.dim_blue"         = theme.base0D;
          "terminal.ansi.dim_magenta"      = theme.base0E;
          "terminal.ansi.dim_cyan"         = theme.base0C;

          # ── Git / file status ──────────────────────────────────────────────
          "conflict"                       = theme.base09;
          "conflict.border"                = theme.base09;
          "conflict.background"            = a theme.base09 "26";
          "created"                        = theme.base0B;
          "created.border"                 = theme.base0B;
          "created.background"             = a theme.base0B "26";
          "deleted"                        = theme.base08;
          "deleted.border"                 = theme.base08;
          "deleted.background"             = a theme.base08 "26";
          "hidden"                         = theme.base03;
          "hidden.border"                  = theme.base03;
          "hidden.background"              = theme.base01;
          "hint"                           = theme.base02;
          "hint.border"                    = theme.base02;
          "hint.background"                = theme.base01;
          "ignored"                        = theme.base03;
          "ignored.border"                 = theme.base03;
          "ignored.background"             = a theme.base03 "26";
          "modified"                       = theme.base0A;
          "modified.border"                = theme.base0A;
          "modified.background"            = a theme.base0A "26";
          "predictive"                     = theme.base03;
          "predictive.border"              = theme.base07;
          "predictive.background"          = theme.base01;
          "renamed"                        = theme.base0C;
          "renamed.border"                 = theme.base0C;
          "renamed.background"             = a theme.base0C "26";

          # ── Diagnostics ────────────────────────────────────────────────────
          "info"                           = theme.base0C;
          "info.border"                    = theme.base0C;
          "info.background"                = a theme.base03 "33";
          "warning"                        = theme.base0A;
          "warning.border"                 = theme.base0A;
          "warning.background"             = a theme.base0A "1f";
          "error"                          = theme.base08;
          "error.border"                   = theme.base08;
          "error.background"               = a theme.base08 "1f";
          "success"                        = theme.base0B;
          "success.border"                 = theme.base0B;
          "success.background"             = a theme.base0B "1f";
          "unreachable"                    = theme.base08;
          "unreachable.border"             = theme.base08;
          "unreachable.background"         = a theme.base08 "1f";

          # ── Version control ────────────────────────────────────────────────
          "version_control.added"          = theme.base0B;
          "version_control.deleted"        = theme.base08;
          "version_control.modified"       = theme.base0A;
          "version_control.renamed"        = theme.base0C;
          "version_control.conflict"       = theme.base09;
          "version_control.conflict_marker.ours"   = a theme.base0B "33";
          "version_control.conflict_marker.theirs" = a theme.base0D "33";
          "version_control.ignored"        = theme.base03;

          # ── Players (multi-cursor colors) ──────────────────────────────────
          players = [
            { cursor = theme.base06; selection = a theme.base03 "40"; background = theme.base06; }
            { cursor = theme.base0E; selection = a theme.base0E "40"; background = theme.base0E; }
            { cursor = theme.base07; selection = a theme.base07 "40"; background = theme.base07; }
            { cursor = theme.base0C; selection = a theme.base0C "40"; background = theme.base0C; }
            { cursor = theme.base0B; selection = a theme.base0B "40"; background = theme.base0B; }
            { cursor = theme.base0A; selection = a theme.base0A "40"; background = theme.base0A; }
            { cursor = theme.base09; selection = a theme.base09 "40"; background = theme.base09; }
            { cursor = theme.base08; selection = a theme.base08 "40"; background = theme.base08; }
          ];

          # ── Syntax highlighting ────────────────────────────────────────────
          # Approximation notes:
          #   "parameter" / "variable.parameter" / "emphasis" / "primary" /
          #   "embedded" use catppuccin's desaturated red (eba0ac) → base08
          #
          #   "punctuation" / "comment" use catppuccin overlay1 (9399b2),
          #   a shade between base02 and base03 → base03
          #
          #   "operator" / "keyword.export" use catppuccin sky (89dceb) → base0C
          #
          #   "string.special.*" / "punctuation.special" / "symbol" /
          #   "character.special" use catppuccin pink (f5c2e7) → base0E
          #
          #   "string.special.symbol" / "constructor" / "comment.todo" /
          #   "punctuation.special.symbol" use catppuccin flamingo (f2cdcd) → base0F
          syntax = {
            "variable"                    = { color = theme.base05; font_style = null; font_weight = null; };
            "variable.builtin"            = { color = theme.base08; font_style = null; font_weight = null; };
            "variable.parameter"          = { color = theme.base08; font_style = null; font_weight = null; };
            "variable.member"             = { color = theme.base0D; font_style = null; font_weight = null; };
            "variable.special"            = { color = theme.base08; font_style = "italic"; font_weight = null; };

            "constant"                    = { color = theme.base09; font_style = null; font_weight = null; };
            "constant.builtin"            = { color = theme.base09; font_style = null; font_weight = null; };
            "constant.macro"              = { color = theme.base0E; font_style = null; font_weight = null; };

            "module"                      = { color = theme.base0A; font_style = "italic"; font_weight = null; };
            "namespace"                   = { color = theme.base0A; font_style = "italic"; font_weight = null; };

            "label"                       = { color = theme.base0C; font_style = null; font_weight = null; };

            "string"                      = { color = theme.base0B; font_style = null; font_weight = null; };
            "string.doc"                  = { color = theme.base0C; font_style = "italic"; font_weight = null; };
            "string.documentation"        = { color = theme.base0C; font_style = null; font_weight = null; };
            "string.regexp"               = { color = theme.base09; font_style = null; font_weight = null; };
            "string.regex"                = { color = theme.base09; font_style = null; font_weight = null; };
            "string.escape"               = { color = theme.base0E; font_style = null; font_weight = null; };
            "string.special"              = { color = theme.base0E; font_style = null; font_weight = null; };
            "string.special.path"         = { color = theme.base0E; font_style = null; font_weight = null; };
            "string.special.symbol"       = { color = theme.base0F; font_style = null; font_weight = null; };
            "string.special.url"          = { color = theme.base06; font_style = "italic"; font_weight = null; };

            "character"                   = { color = theme.base0C; font_style = null; font_weight = null; };
            "character.special"           = { color = theme.base0E; font_style = null; font_weight = null; };

            "boolean"                     = { color = theme.base09; font_style = null; font_weight = null; };
            "number"                      = { color = theme.base09; font_style = null; font_weight = null; };
            "number.float"                = { color = theme.base09; font_style = null; font_weight = null; };
            "float"                       = { color = theme.base09; font_style = null; font_weight = null; };

            "tag"                         = { color = theme.base0D; font_style = null; font_weight = null; };
            "tag.attribute"               = { color = theme.base0A; font_style = "italic"; font_weight = null; };
            "tag.delimiter"               = { color = theme.base0C; font_style = null; font_weight = null; };
            "tag.doctype"                 = { color = theme.base0E; font_style = null; font_weight = null; };

            "type"                        = { color = theme.base0A; font_style = null; font_weight = null; };
            "type.builtin"                = { color = theme.base0E; font_style = "italic"; font_weight = null; };
            "type.definition"             = { color = theme.base0A; font_style = null; font_weight = null; };
            "type.interface"              = { color = theme.base0A; font_style = "italic"; font_weight = null; };
            "type.super"                  = { color = theme.base0A; font_style = "italic"; font_weight = null; };
            "type.class.definition"       = { color = theme.base0A; font_style = null; font_weight = 700; };

            "attribute"                   = { color = theme.base09; font_style = null; font_weight = null; };
            "property"                    = { color = theme.base0D; font_style = null; font_weight = null; };
            "field"                       = { color = theme.base07; font_style = null; font_weight = null; };

            "function"                    = { color = theme.base0D; font_style = null; font_weight = null; };
            "function.builtin"            = { color = theme.base09; font_style = null; font_weight = null; };
            "function.call"               = { color = theme.base0D; font_style = null; font_weight = null; };
            "function.macro"              = { color = theme.base0C; font_style = null; font_weight = null; };
            "function.method"             = { color = theme.base0D; font_style = null; font_weight = null; };
            "function.method.call"        = { color = theme.base0D; font_style = null; font_weight = null; };
            "function.decorator"          = { color = theme.base09; font_style = null; font_weight = null; };

            "constructor"                 = { color = theme.base0F; font_style = null; font_weight = null; };

            "operator"                    = { color = theme.base0C; font_style = null; font_weight = null; };

            "keyword"                     = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.modifier"            = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.type"                = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.coroutine"           = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.function"            = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.operator"            = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.import"              = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.repeat"              = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.return"              = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.debug"               = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.exception"           = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.conditional"         = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.conditional.ternary" = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.directive"           = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.directive.define"    = { color = theme.base0E; font_style = null; font_weight = null; };
            "keyword.export"              = { color = theme.base0C; font_style = null; font_weight = null; };

            "punctuation"                 = { color = theme.base03; font_style = null; font_weight = null; };
            "punctuation.delimiter"       = { color = theme.base03; font_style = null; font_weight = null; };
            "punctuation.bracket"         = { color = theme.base03; font_style = null; font_weight = null; };
            "punctuation.special"         = { color = theme.base0E; font_style = null; font_weight = null; };
            "punctuation.special.symbol"  = { color = theme.base0F; font_style = null; font_weight = null; };
            "punctuation.list_marker"     = { color = theme.base0C; font_style = null; font_weight = null; };

            "comment"                     = { color = theme.base03; font_style = "italic"; font_weight = null; };
            "comment.doc"                 = { color = theme.base03; font_style = "italic"; font_weight = null; };
            "comment.documentation"       = { color = theme.base03; font_style = "italic"; font_weight = null; };
            "comment.info"                = { color = theme.base0C; font_style = "italic"; font_weight = null; };
            "comment.error"               = { color = theme.base08; font_style = "italic"; font_weight = null; };
            "comment.warning"             = { color = theme.base0A; font_style = "italic"; font_weight = null; };
            "comment.warn"                = { color = theme.base0A; font_style = "italic"; font_weight = null; };
            "comment.hint"                = { color = theme.base0D; font_style = "italic"; font_weight = null; };
            "comment.todo"                = { color = theme.base0F; font_style = "italic"; font_weight = null; };
            "comment.note"                = { color = theme.base06; font_style = "italic"; font_weight = null; };

            "diff.plus"                   = { color = theme.base0B; font_style = null; font_weight = null; };
            "diff.minus"                  = { color = theme.base08; font_style = null; font_weight = null; };

            "parameter"                   = { color = theme.base08; font_style = null; font_weight = null; };
            "symbol"                      = { color = theme.base0E; font_style = null; font_weight = null; };

            "text"                        = { color = theme.base05; font_style = null; font_weight = null; };
            "text.literal"                = { color = theme.base0B; font_style = null; font_weight = null; };
            "emphasis"                    = { color = theme.base08; font_style = "italic"; font_weight = null; };
            "emphasis.strong"             = { color = theme.base08; font_style = null; font_weight = 700; };
            "embedded"                    = { color = theme.base08; font_style = null; font_weight = null; };

            "concept"                     = { color = theme.base0C; font_style = null; font_weight = null; };
            "enum"                        = { color = theme.base0C; font_style = null; font_weight = 700; };
            "variant"                     = { color = theme.base08; font_style = null; font_weight = null; };
            "parent"                      = { color = theme.base09; font_style = null; font_weight = null; };

            "hint"                        = { color = theme.base03; font_style = "italic"; font_weight = null; };
            "predictive"                  = { color = theme.base03; font_style = null; font_weight = null; };
            "predoc"                      = { color = theme.base08; font_style = null; font_weight = null; };
            "primary"                     = { color = theme.base08; font_style = null; font_weight = null; };

            "link_text"                   = { color = theme.base07; font_style = null; font_weight = null; };
            "link_uri"                    = { color = theme.base0D; font_style = "italic"; font_weight = null; };

            "title"                       = { color = theme.base05; font_style = null; font_weight = 800; };
          };
        };
      }
    ];
  };

in
{
  # ── Write the theme file ─────────────────────────────────────────────────────
  home.file.".config/zed/themes/${themeName}.json" = {
    force = true;
    text = themeJson;
  };
}
